### PR TITLE
[WIP] docs do not work

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Hi,

1. I notices both here the link doesn't work, and not sure where to report (issues tab missing so (mis)using PR).

2. Also docs to install here didn't work: https://www.mlpack.org/doc/mlpack-git/doxygen/julia_quickstart.html

```
] mlpack_jll
```

worked for me, not sure if that should be used and/or this package yet to be registered?

**Comment by rcurtin** [comment]
You're just a little too early. :smile:

The Julia bindings aren't formally released into mlpack stable until mlpack 3.3.0, and so that link won't exist until 3.3.0 is released, but 3.3.0 won't be released until the mlpack.jl package is available via `Pkg`.  So there is a little bit of a chicken-egg problem. :)

BTW the readme for this repo (just a few lines under where you modified :)) says that issues should be reported to the main mlpack repository. :+1:

**Comment by rcurtin** [comment]
Also here is the julia registry PR: https://github.com/JuliaRegistries/General/pull/9767 , so once that's resolved then mlpack 3.3.0 will be released a little later.

Although actually I answered this forgetting that the Julia documentation actually *is* already available:
https://www.mlpack.org/doc/mlpack-git/julia_documentation.html

So I updated the readme in bf1540c with that link.

**Comment by rcurtin** [comment]
This is fixed, so I'll go ahead and close it.  Thanks again for the report.

**Pull request closed without merging**
